name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: rustup component add rustfmt
    - name: Rustfmt
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build --verbose
